# Generated by Django 5.2.6 on 2026-03-12 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='queue',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
